version: "3.9"

services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - shared_uploads:/myapp/uploads
    environment:
      - UPLOADS_ROOT=/myapp/uploads
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /myapp
        - action: rebuild
          path: ./backend/reqs.txt

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - shared_uploads:/myapp/uploads
    environment:
      - UPLOADS_ROOT=/myapp/uploads
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /myapp
        - action: rebuild
          path: ./frontend/reqs.txt

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  db_data:
  shared_uploads:
